### ISSUE TITLE
[Example] Two separated bundles for front/admin modules

### ISSUE THREAD

**Issue by JanMikes** [trainit/2018-03-nette-webpack#1]
Is it worth separating front/admin assets or just bundle them all together in one app.js?

Etc in admin there are datetimepicker and other plugins that are not used on front -> i want to save user's data usage.

**Comment by f3l1x** [comment]
Sure, It can be done using more entry points.

https://github.com/trainit/2018-03-nette-webpack/blob/45bcdc4d84b846d105df08d2a97f051a7854c471/webpack.config.js#L6

**Comment by f3l1x** [comment]
I've added it on roadmap list.

**Comment by f3l1x** [comment]
Hi @JanMikes 

Solved via changes in webpack.config.js - https://github.com/trainit/2018-03-nette-webpack/blob/ec153046715d824064c51562fcd0116419d4f067/webpack.config.js#L38-L39

And appropriate changes in admin layout - https://github.com/trainit/2018-03-nette-webpack/blob/ec153046715d824064c51562fcd0116419d4f067/app/presenters/templates/Admin/%40layout.latte#L1-L9
