### ISSUE TITLE
Add webpack-dev-server?

### ISSUE THREAD

**Issue by adaamz** [trainit/2018-03-nette-webpack#5]
Hi,
how would you add webpack-dev-server to php webserver?
Will this example show how to do it?

**Comment by f3l1x** [comment]
We have it in the plan. See the upcomming training at https://www.akademie42.cz.

**Comment by CZechBoY** [comment]
Nice to hear. Unfortunately I cannot find the training :disappointed:

**Comment by f3l1x** [comment]
Training lessons https://www.akademie42.cz/kurz/milan-sulc-vue-js-pomocnik-nejen-s-novou-single-page-aplikaci.

Closing it here. Webpack dev server will be added (maybe) in the future to official [nette/examples](https://github.com/nette/examples) repository.
