### ISSUE TITLE
Simple inject js/css into @layout.latte

### ISSUE THREAD

**Issue by acqsk** [trainit/2018-03-nette-webpack#89]
Hi Guys, thanks for really good pattern to use Webpack with Nette. In this example, you have defined the paths to css/html in @layout.latte file. But, If I want to generate hash to filename during each build of app, I need to generate the links to js/css in header/footer dynamically.

I know, that somebody created Nette plugin for this functionality. The plugin reads list of files from JS map file and adds it into the header.

But what do you think about solution to use webpack-html-plugin and make new functionality to this plugin (add basePath option), which will replace the path from webpack output (ONLY in this plugin) to defined path, for example:

webpack.output.basepath will be defined to 
`webpack.output.basepath: './' (relative path)`

and then webpack html plugin basePath will be defined to
`basePath: '{$basePath}/dist/'`

...and {$basePath} will be replaced to absolute path by nette/latte.

please, check line 228
https://gist.github.com/acqsk/e0f840798f8b3f09135a77add56df140

rendered html by your plugin from template, line 5 and line 213
https://gist.github.com/acqsk/46779f1d5c5441573c04496a8ef3ad30

What do you think about it? It's a good or stupid idea? ...or do you have another simple idea to make this?

**Comment by f3l1x** [comment]
Hey, I've looked your gist and I am ok with this way. 

Personally I use manifest-like way with this webpack pluging (https://github.com/danethurber/webpack-manifest-plugin).

Thanks for your idea anyway.
